// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Doctor struct {
	ID          int64
	Name        string
	Crm         string
	AverageRate int32
	CreatedAt   sql.NullTime
}

type Doula struct {
	ID          int64
	Name        string
	AverageRate int32
	CreatedAt   sql.NullTime
}

type Midwife struct {
	ID          int64
	Name        string
	AverageRate int32
	CreatedAt   sql.NullTime
}

type Place struct {
	ID             int64
	Name           string
	Addres         sql.NullString
	City           string
	State          string
	Country        sql.NullString
	AverageRate    int32
	Classification sql.NullString
	CreatedAt      sql.NullTime
}

type Review struct {
	ID             int64
	UserID         sql.NullInt32
	Title          string
	Content        string
	Date           time.Time
	Classification string
	Amount         sql.NullString
	OverallRate    int32
	Insurance      sql.NullString
	PlaceID        int32
	PlaceRate      int32
	DoctorID       int32
	DoctorRate     int32
	MidwifeID      sql.NullInt32
	MidwifeRate    sql.NullInt32
	DoulaID        sql.NullInt32
	DoulaRate      sql.NullInt32
	Team           sql.NullString
	TeamRate       sql.NullInt32
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Image          sql.NullString
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Password  string
	CreatedAt sql.NullTime
}
