version: "3.9"

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    hostname: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - im

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports: 
      - "6543:6543"
    depends_on:
      - postgres
    networks:
      - im      

  api:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - im

volumes:
  data:
    driver: local

networks:
  im:
    driver: bridge