version: "3.9"

services:

  postgres_db:
    image: postgres:12-alpine
    restart: always
    hostname: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - im

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports: 
      - "6543:6543"
    depends_on:
      - postgres_db
    networks:
      - im      

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgres_db
    networks:
      - im

volumes:
  pgdata:

networks:
  im:
    driver: bridge