// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CountDoctorReviews(ctx context.Context, doctorID int32) (int64, error)
	CountPlaceReviews(ctx context.Context, placeID int32) (int64, error)
	CreateDoctor(ctx context.Context, arg CreateDoctorParams) (Doctor, error)
	CreatePlace(ctx context.Context, arg CreatePlaceParams) (Place, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDoctor(ctx context.Context, id int64) error
	DeletePlace(ctx context.Context, id int64) error
	DeleteReview(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetDoctor(ctx context.Context, id int64) (Doctor, error)
	GetPlace(ctx context.Context, id int64) (Place, error)
	GetReview(ctx context.Context, id int64) (Review, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListDoctorReviews(ctx context.Context, doctorID int32) ([]Review, error)
	ListDoctors(ctx context.Context, arg ListDoctorsParams) ([]Doctor, error)
	ListPlaces(ctx context.Context) ([]Place, error)
	ListReviews(ctx context.Context) ([]Review, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateDoctor(ctx context.Context, arg UpdateDoctorParams) error
	UpdatePlace(ctx context.Context, arg UpdatePlaceParams) error
	UpdateReview(ctx context.Context, arg UpdateReviewParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
