name: Go

on:
  push:
    branches: [ "master", "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

  test:
    name: Test
    runs-on: ubunto-latest

    steps:
      - uses: actions/checkout@v3
      with:
        go-version: 1.19

      - name: Test
      - run: make test          

  golangci:
   name: lint
   runs-on: ubuntu-latest
   steps:
     - uses: actions/setup-go@v3
       with:
         go-version: 1.17
     - uses: actions/checkout@v3
     - name: golangci-lint
       uses: golangci/golangci-lint-action@v3
       with:
         version: v1.29    